### ISSUE TITLE
TypeError: peak_pick() takes 1 positional argument but 7 were given

### ISSUE THREAD

**Issue by xjgby** [LaoADe/music_point#1]
Traceback (most recent call last):
  File "E:\python\main-sound.py", line 143, in <module>
    main()
  File "E:\python\main-sound.py", line 26, in main
    peaks = librosa.util.peak_pick(onset_env, 1, 1, 1, 1, 0.8, 5)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: peak_pick() takes 1 positional argument but 7 were given

我查了peak_pick是对的，但不知为何报错。

**Comment by LaoADe** [comment]
librosa更新了
`peak_pick(
    x: np.ndarray,
    *,
    pre_max: int,
    post_max: int,
    pre_avg: int,
    post_avg: int,
    delta: float,
    wait: int,
)`
用关键字参数传参
